# Generated by Django 5.0.6 on 2024-05-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_reservation_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="year_of_study",
            field=models.IntegerField(null=True),
        ),
    ]
