# Generated by Django 5.0.6 on 2024-05-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_reservation_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="reservation_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="reservation_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
