# Generated by Django 5.0.6 on 2024-06-01 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bus_reservation_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="seat_number",
        ),
    ]
