# Generated by Django 5.0.6 on 2024-06-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_reservation_app", "0002_remove_schedule_seat_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="seat_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
