# Generated by Django 5.0.6 on 2024-05-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_reservation_app", "0002_alter_schedule_reservation_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="ticket",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
